envelop: overide default value for `maxheaderlen`
with python <= 3.7.3 stringify mail can produce the following error:

  File "/usr/lib/python3.7/email/_header_value_parser.py", line 2729, in _fold_as_ew
    first_part = to_encode[:text_space]
  TypeError: slice indices must be integers or None or have an __index__ method

this is because `maxlen` parameter default to `float("+inf")` which lead to some
arithmetic errors. This "bug" is fix since python3.7.4, but as we need to support
previous version we should enforce a truthy value for `maxheaderlen` to not default
on `float("+inf")`